apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
spec:
  replicas: 2 # We are asking K8s to run TWO copies for high availability!
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      containers:
      - name: java-backend
        image: adityadh2425/java-backend:latest
        imagePullPolicy: IfNotPresent # Crucial: Tells K8s to use your local Mac image, not search the internet
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-backend-service
spec:
  selector:
    app: java-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080