apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-frontend
  template:
    metadata:
      labels:
        app: node-frontend
    spec:
      containers:
      - name: node-frontend
        image: adityadh2425/node-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-frontend-service
spec:
  type: LoadBalancer # Exposes this service outside the cluster
  selector:
    app: node-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000